### ISSUE TITLE
STEP files for ease of compatibility?

### ISSUE THREAD

**Issue by happycncer** [Savage-Sabrina/DIY_SolenoidGraver#1]
Is there any possibility of having the CAD Files (listed under PreviousIdeas) available in STEP format? I only ask as this can be imported more readily by many other CAD Software products. It's predominately the parts needing to be 3D printed that are the most difficult, as they are mostly all shown in the FreeCad format - which is not particularly friendly when trying to import them into other CAD applications.

**Comment by Savage-Sabrina** [comment]
The files were converted and uploaded to the same folder in order to make the compatibility easier.
